# Generated by Django 5.1.6 on 2025-02-19 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='passport',
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Applications', to='Alehson.category'),
        ),
    ]
