# Generated by Django 5.1.6 on 2025-02-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Passport_number',
            new_name='passport_number',
        ),
    ]
