# Generated by Django 5.1.6 on 2025-02-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0002_category_application_card_number_alter_news_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='img',
        ),
        migrations.AddField(
            model_name='application',
            name='images',
            field=models.ManyToManyField(related_name='applications', to='Alehson.images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='Images/Application/'),
        ),
    ]
