# Generated by Django 5.1.6 on 2025-03-18 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0002_about_home_sitehelp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=13)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='home',
            old_name='description',
            new_name='description_thick',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='image2',
            new_name='iamge1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image4',
        ),
        migrations.AddField(
            model_name='home',
            name='description_thin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ImagesHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/home/')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Alehson.home')),
            ],
        ),
    ]
