# Generated by Django 5.1.6 on 2025-03-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0002_alter_subcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='view_count',
        ),
    ]
