# Generated by Django 5.1.6 on 2025-03-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0003_contact_rename_description_home_description_thick_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/categories_settings/', verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images/Help')),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='about',
            old_name='description',
            new_name='description_thick',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='description_thick',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='description_thin',
        ),
        migrations.RemoveField(
            model_name='home',
            name='iamge1',
        ),
        migrations.AddField(
            model_name='about',
            name='description_thin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='Images/About'),
        ),
    ]
