# Generated by Django 5.1.6 on 2025-02-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0003_remove_application_img_application_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='images',
        ),
        migrations.AddField(
            model_name='images',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Applications_images', to='Alehson.application'),
            preserve_default=False,
        ),
    ]
