# Generated by Django 5.1.6 on 2025-02-26 15:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0003_alter_news_slug_alter_subcategory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(),
        ),
    ]
