# Generated by Django 5.1.6 on 2025-02-20 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0003_news_view_count_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Alehson.subcategory'),
        ),
    ]
