# Generated by Django 5.1.6 on 2025-02-18 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0004_remove_application_images_images_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Alehson.application'),
        ),
    ]
