# Generated by Django 5.1.6 on 2025-02-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0004_application_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='sub_category',
        ),
    ]
