# Generated by Django 5.1.6 on 2025-03-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0004_categorysettings_help_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplecationSetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images/AplecationSetings')),
            ],
        ),
        migrations.CreateModel(
            name='petitionsubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iamge', models.ImageField(blank=True, null=True, upload_to='Images/petitionsubmit')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
        migrations.AddField(
            model_name='about',
            name='description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
