# Generated by Django 5.1.6 on 2025-03-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0004_application_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
