# Generated by Django 5.1.6 on 2025-03-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0005_aplecationsetings_petitionsubmit_remove_home_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/home/'),
        ),
    ]
