# Generated by Django 5.1.6 on 2025-03-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0005_remove_application_view_count_remove_news_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
