# Generated by Django 5.1.6 on 2025-03-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0006_home_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='main_title',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='title_2',
            new_name='main_title2',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='description_2',
            new_name='mission_description',
        ),
        migrations.AddField(
            model_name='about',
            name='mission_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='vision_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='vision_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
