# Generated by Django 5.1.6 on 2025-02-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0006_alter_application_category_alter_application_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eskizsms',
        ),
        migrations.RemoveField(
            model_name='application',
            name='code',
        ),
        migrations.AddField(
            model_name='application',
            name='Passport_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
