# Generated by Django 5.1.6 on 2025-03-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0007_rename_title_about_main_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iamge', models.ImageField(blank=True, null=True, upload_to='Images/ContactSettings')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='about',
            old_name='description_thick',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='main_title2',
            new_name='thick_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='description_thin',
        ),
    ]
