# Generated by Django 5.1.6 on 2025-02-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0007_delete_eskizsms_remove_application_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='images',
        ),
    ]
