# Generated by Django 5.1.6 on 2025-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0008_contactsettings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsettings',
            old_name='iamge',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='petitionsubmit',
            old_name='iamge',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
