# Generated by Django 5.1.6 on 2025-02-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0008_rename_image_images_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='image',
        ),
    ]
