# Generated by Django 5.1.6 on 2025-02-25 13:07

import Alehson.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alehson', '0009_rename_images_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=Alehson.models.user_directory_path),
        ),
    ]
